<?php

namespace FrontendBundle\Repository;

/**
 * ProductoCompradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoCompradoRepository extends \Doctrine\ORM\EntityRepository
{
}
