imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MWSimpleAdminCrudBundle/Resources/config/config.yml" }
    - { resource: "@BackendBundle/Resources/config/services.yml" }
    - { resource: "@FrontendBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

knp_paginator:
    page_range: 10                     # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        # pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # bootstrap 3 sliding pagination controls template
        pagination: MWSimpleAdminCrudBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # bootstrap 3 sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: MWSimpleAdminCrudBundle:Menu:knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by defaul
mw_simple_admin_crud:
    setting: { site_name: Administración de Arphos, fos_user: false } # Default:: site_theme: bootstrap, site_name: AdminCrud, site_view_layout: 'MWSimpleAdminCrudBundle::layout.html.twig', site_view_footer: '::footer.html.twig', fos_user: false, menu_horizontal: false
    menu_setting: { id: side-menu, class: nav } # use id: side-menu and class: nav. If is horizontal use class: nav navbar-nav
    menu:
        child: { name: inicio, url: mws_admin_crud_menu, id: inicio, icon: glyphicon glyphicon-home }
        categoria: { name: Categoria, url: categoria, id: inicio, icon: glyphicon glyphicon-home }
        producto: { name: Producto, url: producto, id: inicio, icon: glyphicon glyphicon-home }
        estacion: { name: Estacion, url: estacion, id: inicio, icon: glyphicon glyphicon-home }
        mensaje: { name: Mensaje, url: mensaje, id: inicio, icon: glyphicon glyphicon-home }
        turno: { name: Turno, url: turno, id: inicio, icon: glyphicon glyphicon-home }
        actividad: { name: Actividad, url: actividad, id: inicio, icon: glyphicon glyphicon-home }
        #child2:  
        #    name: help
        #    url: null
        #    id: help
        #    subMenu:
        #        indice:
        #            name: indice
        #            url: admin_indice
        #            icon: glyphicon glyphicon-home
        #            roles: ['ROLE_ADMIN']
        #    roles: ['ROLE_USER']
        #child3: { name: Usuarios, url: admin_usuario, id: usuario, roles: ['ROLE_SUPERADMIN'], icon: glyphicon glyphicon-user }

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        banner_image:
            uri_prefix:         /images/banner
            upload_destination: %kernel.root_dir%/../web/images/banner
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        slide_image:
            uri_prefix:         /images/slide
            upload_destination: %kernel.root_dir%/../web/images/slide
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        producto_image:
            uri_prefix:         /images/producto
            upload_destination: %kernel.root_dir%/../web/images/pagina
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        noticia_image:
            uri_prefix:         /images/noticia
            upload_destination: %kernel.root_dir%/../web/images/noticia
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        resource_image:
            uri_prefix:         /images/resource
            upload_destination: %kernel.root_dir%/../web/images/resource
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        documento_image:
            uri_prefix:         /images/documento
            upload_destination: %kernel.root_dir%/../web/images/documento
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        menu_item_image:
            uri_prefix:         /images/item
            upload_destination: %kernel.root_dir%/../web/images/item
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
