backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    # resource: "@EasyAdminExtensionBundle/Controller/AdminController.php"
    resource: '@BackendBundle/Controller/AdminController.php'
    type:     annotation
    prefix:   /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# DEBE IR AL FINAL
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MWSimpleAdminCrudBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*\/$
        _method: GET
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"