easy_admin:
    design:
        brand_color: '#d5bbaa'
        assets:
            favicon:
                path: '/assets/logotipo.png'

        # assets:
        #     css:
        #         # HTTP protocol-relative URL
        #         - "assets/css/backend.css"
        #         # estilos para las tablas
        #         - "assets/table/css/animate.css"
        #         - "assets/table/css/select2.min.css"
        #         - "assets/table/css/perfect-scrollbar.css"
        #         - "assets/table/css/main.css"
        #         - "assets/table/css/util.css"
        #     js:
        #         # javascript para las tablas
        #         - "assets/table/js/main.js"
        #         - "assets/table/js/select2.min.js"
        #         - "assets/table/js/popper.js"

        menu:
            # - { label: 'Panel Principal', route: 'dashboard', icon: 'caret-down', default: true }
            - label: 'Gesti贸n de Productos'
              # icon: 'newspaper'
              children:
                - { label: 'Productos', entity: 'Producto' }
                - { label: 'Categorias', entity: 'Categoria' }
                - { label: 'Talles', entity: 'Talle' }
            - { label: 'Gesti贸n de Compras', entity: 'Compra' }
            - { label: 'Gesti贸n de Turnos', entity: 'Turno' }
            - { label: 'Gesti贸n de Consultas', entity: 'Mensaje' }


            