easy_admin:
    design:
        brand_color: '#d5bbaa'
        assets:
            favicon:
                path: '/assets/logotipo.png'

        # assets:
        #     css:
        #         # HTTP protocol-relative URL
        #         - "assets/css/backend.css"
        #         # estilos para las tablas
        #         - "assets/table/css/animate.css"
        #         - "assets/table/css/select2.min.css"
        #         - "assets/table/css/perfect-scrollbar.css"
        #         - "assets/table/css/main.css"
        #         - "assets/table/css/util.css"
        #     js:
        #         # javascript para las tablas
        #         - "assets/table/js/main.js"
        #         - "assets/table/js/select2.min.js"
        #         - "assets/table/js/popper.js"

        menu:
            # - { label: 'Panel Principal', route: 'dashboard', icon: 'caret-down', default: true }
            - label: 'Gestión de Productos'
              icon: 'paw'
              children:
                - { label: 'Productos', entity: 'Producto',icon: 'paw' }
                - { label: 'Categorias', entity: 'Categoria',icon: 'paw' }
                - { label: 'Talles', entity: 'Talle', icon: 'paw' }
            - { label: 'Gestión de Compras', entity: 'Compra',icon: 'paw' }
            - { label: 'Gestión de Turnos', entity: 'Turno',icon: 'paw' }
            - { label: 'Gestión de Consultas', entity: 'Mensaje',icon: 'paw' }
            - { label: 'Galería', entity: 'Galeria',icon: 'paw' }
            - label: 'Gestión de Paginas'
              icon: 'paw'
              children:
                - { label: 'Paginas', entity: 'Pagina' ,icon: 'paw'}
                - { label: 'Categorias de Pagina', entity: 'CategoriaPagina',icon: 'paw' }

            