easy_admin:
    entities:
        CategoriaPagina:
            class: BackendBundle\Entity\CategoriaPagina
            label: 'Categoria de Paginas'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Categorias"
                actions:
                    - { name: 'new', label: 'Crear Categoría Pagina'}
                fields:
                    - { property: id, label: 'Nro. de Categoría',css_class: 'col-md-1'}
                    - { property: 'titulo' , label: 'Título',css_class: 'col-md-2'}
                    - { property: 'categoriaPadre' , label: 'Categoría Padre',css_class: 'col-md-2'}
                    - { property: 'subCategorias' , label: 'SubCategorias',css_class: 'col-md-2', type: simple_array}
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                title: 'Crear Categoría'
                fields: 
                    - { type: 'group', css_class: 'col-sm-12', label: 'Categoría' }
                    - { type: 'divider' }
                    - { property: 'titulo' , label: 'Título',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'categoriaPadre' , label: 'Categoría Padre',css_class: 'col-md-6'}
                    
            show:
                fields:
                    - {property: id, label: 'Nro. de Categoría',css_class: 'col-md-6'}
                    - { property: 'titulo' , label: 'Título',css_class: 'col-md-6'}
                    - { property: 'categoriaPadre' , label: 'Categoría Padre',css_class: 'col-md-6'}
                    - { property: 'subCategorias' , label: 'SubCategorias',css_class: 'col-md-6'}
            edit:
                title: 'Editar Categoría'  
