easy_admin:
    entities:
        Mensaje:
            class: BackendBundle\Entity\Mensaje
            label: 'Mensaje'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Mensaje"
                fields:
                    - { property: id, label: 'Nro de Mensaje'}
                    - { property: 'fecha' , label: 'Fecha' , type: datetime}
                    - { property: apellido, label: 'Apellido'}
                    - { property: 'nombre' , label: 'Nombre'}
                    - { property: 'telefono' , label: 'telefono'}
                    - { property: 'email' , label: 'Email',type: email}
            show:
                fields:
                    - { property: id, label: 'Nro de Mensaje'}
                    - { property: 'fecha' , label: 'Fecha' , type: datetime}
                    - { property: apellido, label: 'Apellido'}
                    - { property: 'nombre' , label: 'Nombre'}
                    - { property: 'telefono' , label: 'telefono'}
                    - { property: 'email' , label: 'Email',type: email}
                    - { property: 'mensaje' , label: 'mensaje' , type: 'text'}