easy_admin:
    entities:
        Pagina:
            class: BackendBundle\Entity\Pagina
            label: 'pagina'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Paginas"
                fields:
                    - id
                    - { property: 'publicado' , label: 'Publicado', type: 'toggle'}
                    - { property: 'categoria', label: 'categoria'}
                    - { property: 'titulo' , label: 'Título', type: 'text'}
                    - { property: 'imagen', type: 'image', base_path: '%path.imagenesPaginas%' }
                    - { property: 'fechaCreacion', label: 'Creación', type: 'date' }
                    - { property: 'fechaModificacion', label: 'Modificación', type: 'date'}
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                title: 'Crear una Pagina'
                fields: 
                    - { type: 'group', css_class: 'col-sm-12', label: 'Crear un nuevo post' }
                    - { property: publicado,css_class: 'col-md-12'}
                    - { property: 'categoria', label: 'Categoria',css_class: 'col-md-12'}
                    - { property: 'titulo',label: 'Título',css_class: 'col-md-12'}
                    - { property: 'introduccion', label: 'Introducción',type: "ckeditor",css_class: 'col-md-12'}
                    - { property: 'desarrollo', type: "ckeditor",css_class: 'col-md-12'}
                    - { property: 'imageFile', type: 'vich_image' , label: 'Imagen Principal',css_class: 'col-md-6'}
                    - { type: 'group', css_class: 'col-md-12', label: "Galeria" }
                    - { property: 'resources' , label: "Galeria de imagenes" ,type: 'collection' ,type_options: { entry_type: '\BackendBundle\Form\ResourceType', by_reference: false }}
            show:
                fields:
                    - id
                    - { property: 'publicado' , label: 'Publicado', type: 'toggle'}
                    - { property: 'categoria', label: 'categoria'}
                    - { property: 'titulo' , label: 'Título', type: 'text'}
                    - { property: 'introduccion', label: 'Introducción',type: "text",css_class: 'col-md-12'}
                    - { property: 'desarrollo', type: "text"}
                    - { property: 'imagen', type: 'image', base_path: '%path.imagenesPaginas%' }
                    # - { property: 'resources' ,label: 'Galeria', template: 'resource_field.html.twig',css_class: 'col-md-12' }
                    - { property: 'fechaCreacion', label: 'Creación', type: 'date' }
                    - { property: 'fechaModificacion', label: 'Modificación', type: 'date'}
            edit:
                title: 'Editar Pagina'
