easy_admin:
    entities:
        Producto:
            class: BackendBundle\Entity\Producto
            label: 'Producto'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Producto"
                fields:
                    - {property: id, label: 'Nro de Inventario',css_class: 'col-md-1'}
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-2'}
                    - { property: 'fechaCreacion' , label: 'Fecha de Creación',css_class: 'col-md-2'}
                    - { property: 'fechaModificacion' , label: 'Fecha de Modificación',css_class: 'col-md-2'}
                    - { property: 'stock',label: 'Stock' ,css_class: 'col-md-2' }
                    - { property: 'precio' , label: 'Precio',css_class: 'col-md-12'}
                    - { property: 'imagen',label: 'Imagen Principal' , type: 'image', base_path: '%path.imagenesProducto%',css_class: 'col-md-2' }
               
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                title: 'Crear un Producto'
                fields: 
                    - { type: 'group', css_class: 'col-sm-12', label: 'General' }
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'stock',label: 'Stock',css_class: 'col-md-6'  }
                    - { type: 'divider' }
                    - { property: 'precio' , label: 'Precio',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'esNovedad' , label: 'Novedad',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'color', label: 'Color', type: 'choice', type_options: { choices: { 'Sin Color': 'Incoloro', 'rojo': 'rojo', 'azul': 'azul', 'amarillo': 'amarillo', 'blanco': 'blanco', 'negro': 'negro', 'verde': 'verde', 'violeta': 'violeta', 'naranja': 'naranja', 'rosa': 'rosa' } },css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'categorias',label: 'Categorias',css_class: 'col-md-6'  } 
                    - { type: 'divider' }
                    - { property: 'talles',label: 'Talles' ,css_class: 'col-md-6' } 
                    - { type: 'divider' }
                    - { property: 'coleccion',label: 'Colección' ,css_class: 'col-md-6' }
                    - { type: 'divider' }
                    - { type: 'group', css_class: 'col-sm-12', label: 'Descripción del Producto' }
                    - { property: 'descripcion', type: "ckeditor", label: 'Descripción',css_class: 'col-md-12'}
                    - { type: 'group', css_class: 'col-sm-12', label: 'Imagenes' }
                    - { property: 'imageFile' , label: "Imagen Principal" ,type: 'vich_image',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'resources' , label: "Galeria de imagenes" ,type: 'collection' ,type_options: { entry_type: 'BackendBundle\Form\ResourceType', by_reference: false },css_class: 'col-md-6'}
            show:
                fields:
                    - {property: id, label: 'Nro de Inventario'}
                    - { property: 'nombre' , label: 'Nombre'}
                    - { property: 'fechaCreacion' , label: 'Fecha de Creación'}
                    - { property: 'fechaModificacion' , label: 'Fecha de Modificación'}
                    - { property: 'stock',label: 'Stock'  }
                    - { property: 'precio' , label: 'Precio'}
                    - { property: 'esNovedad' , label: 'Novedad'}
                    - { property: 'color', label: 'Color'}
                    - { property: 'categorias',label: 'Categorias'  } 
                    - { property: 'talles',label: 'Talles'  } 
                    - { property: 'coleccion',label: 'Colección'  }
                    - { property: 'descripcion', type: "text", css_class: 'col-md-12', label: 'Descripción'}
                    - { property: 'imagen',label: 'Imagen Principal' , type: 'image', base_path: '%path.imagenesProducto%', css_class: 'col-md-12' }
                    - { property: 'resources' ,label: 'Galeria', template: 'resource_field.html.twig',css_class: 'col-md-12' }

                edit:
                title: 'Editar Producto' 