easy_admin:
    entities:
        Talle:
            class: BackendBundle\Entity\Talle
            label: 'Talles'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Talles"
                fields:
                    - { property: 'nombre' , label: 'talle'}

                title: 'Crear un Banner'
                fields: 
                    - { type: 'group', css_class: 'col-sm-12', label: 'Descripción del Talle' }
                    - { property: 'nombre',label: 'Talle', css_class: 'col-md-12'}
            show:
                fields:
                    - { property: 'nombre',label: 'Talle', css_class: 'col-md-12'}
                edit:
                title: 'Editar Talle'  