easy_admin:
    entities:
        Turno:
            class: BackendBundle\Entity\Turno
            label: 'Turno'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Turnos"
                fields:
                    - { property: 'id', label: 'Nro. de Turno', css_class: 'col-md-6'}
                    - { property: 'nombre' , label: 'Nombre', css_class: 'col-md-6'}
                    - { property: 'apellido' , label: 'Apellido', css_class: 'col-md-6'}
                    - { property: 'diayhorapiso' , label: 'Inicio Turno', format: 'd/m/Y g:i A', css_class: 'col-md-6'}
                    - { property: 'diayhoratecho' , label: 'Final Turno', format: 'd/m/Y g:i A', css_class: 'col-md-6'}
                    - { property: 'direccion' , label: 'Dirección', css_class: 'col-md-6'}
                    - { property: 'correo' , label: 'Correo', css_class: 'col-md-6'}
                    - { property: 'telefono' , label: 'Teléfono', css_class: 'col-md-6'}
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                title: 'Crear un Turno'
                fields: 
                    - { type: 'group', css_class: 'col-md-12', label: 'Descripción del Turno' }
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    #- { property: 'diayhora' , label: 'Día y Hora',type: 'date', type_options: { widget: 'single_text' },css_class: 'col-md-6'}
                    - { property: 'diayhorapiso' , label: 'Día y Hora',type: 'datetime', css_class: 'col-md-6', type_options: { widget: 'text' }}
                    - { property: 'diayhoratecho' , label: 'Día y Hora',type: 'datetime', css_class: 'col-md-6',  type_options: {widget: 'choice' , format: 'yyyy-MM-dd'}}
                    - { type: 'divider' }
                    - { property: 'apellido' , label: 'Apellido',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'direccion' , label: 'Dirección',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'correo' , label: 'Correo',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'telefono' , label: 'Teléfono',css_class: 'col-md-6', type: 'Symfony\Component\Form\Extension\Core\Type\TelType'}
            show:
                fields:
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-6'}
                    - { property: 'diayhorapiso' , label: 'Inicio Turno', format: 'd/m/Y g:i A', css_class: 'col-md-6'}
                    - { property: 'diayhoratecho' , label: 'Final Turno', format: 'd/m/Y g:i A', css_class: 'col-md-6'}
                    - { property: 'apellido' , label: 'Apellido',css_class: 'col-md-6'}
                    - { property: 'direccion' , label: 'Dirección',css_class: 'col-md-6'}
                    - { property: 'correo' , label: 'Correo',css_class: 'col-md-6'}
                    - { property: 'telefono' , label: 'Teléfono',css_class: 'col-md-6'}
            edit:
                title: 'Editar Turno'  
