easy_admin:
    entities:
        Turno:
            class: BackendBundle\Entity\Turno
            label: 'Turno'
            role: ROLE_ADMIN
            # role_prefix: ROLE_PAGINA
            # help: 'Global message displayed in all views'
            list:
                title: "Turnos"
                fields:
                    - { property: 'id', label: 'Nro. de Turno', css_class: 'col-md-6'}
                    - { property: 'cliente', label: 'Cliente', css_class: 'col-md-6'}
                    - { property: 'nombre' , label: 'Nombre', css_class: 'col-md-6'}
                    - { property: 'apellido' , label: 'Apellido', css_class: 'col-md-6'}
                    - { property: 'dia' , label: 'Dia', format: 'd/m/Y', css_class: 'col-md-10'}
                    - { property: 'hora', label: 'Hora de Inicio', css_class: 'col-md-6'}
                    - { property: 'horatecho', label: 'Hora de Fin', css_class: 'col-md-6'}
                    - { property: 'direccion' , label: 'Dirección', css_class: 'col-md-6'}
                    - { property: 'correo' , label: 'Correo', css_class: 'col-md-6'}
                    - { property: 'telefono' , label: 'Teléfono', css_class: 'col-md-6'}

            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                title: 'Crear un Turno'
                fields: 
                    - { type: 'group', css_class: 'col-md-12', label: 'Descripción del Turno' }
                    - { property: 'cliente', label: 'Cliente', css_class: 'col-md-6'}
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-6'}
                    - { property: 'apellido' , label: 'Apellido',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'dia' , label: 'Día',type: 'date', css_class: 'col-md-12'}
                    - { property: 'hora' , label: 'Hora de Inicio', css_class: 'col-md-12'}
                    - { property: 'horatecho' , label: 'Hora Fin'    , css_class: 'col-md-12'}
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'apellido' , label: 'Apellido',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'direccion' , label: 'Dirección',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'correo' , label: 'Correo',css_class: 'col-md-6'}
                    - { type: 'divider' }
                    - { property: 'telefono' , label: 'Teléfono',css_class: 'col-md-6', type: 'Symfony\Component\Form\Extension\Core\Type\TelType'}
            show:
                fields:
                    - { property: 'cliente', label: 'Cliente', css_class: 'col-md-6'}
                    - { property: 'nombre' , label: 'Nombre',css_class: 'col-md-6'}
                    - { property: 'apellido' , label: 'Apellido',css_class: 'col-md-6'}
                    - { property: 'dia' , label: 'Dia', format: 'd/m/Y', css_class: 'col-md-6'}
                    - { property: 'hora' , label: 'Hora de Inicio',css_class: 'col-md-6'}
                    - { property: 'horatecho', label: 'Hora de Fin', css_class: 'col-md-6'}
                    - { property: 'direccion' , label: 'Dirección',css_class: 'col-md-6'}
                    - { property: 'correo' , label: 'Correo',css_class: 'col-md-6'}
                    - { property: 'telefono' , label: 'Teléfono',css_class: 'col-md-6'}
            edit:
                title: 'Editar Turno'  
