<?php

namespace BackendBundle\Repository;

/**
 * EstacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstacionRepository extends \Doctrine\ORM\EntityRepository
{
}
