<?php

namespace BackendBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalleRepository extends \Doctrine\ORM\EntityRepository
{
}
