entityName: 'Categoria'
entity: 'BackendBundle\Entity\Categoria'
repository: 'BackendBundle:Categoria'
paginate: true
index: 'categoria'
view_index: 'BackendBundle:categoria:index.html.twig'
new: 'categoria_new'
create: 'categoria_create'
view_new: 'BackendBundle:categoria:new.html.twig'
edit: 'categoria_edit'
update: 'categoria_update'
view_edit: 'BackendBundle:categoria:edit.html.twig'
show: 'categoria_show'
view_show: 'BackendBundle:categoria:show.html.twig'
delete: 'categoria_delete'
export: 'categoria_export'
sessionFilter: 'CategoriaControllerFilter'
saveAndAdd: true
validator: true
fieldsindex:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        export: true
    a.titulo:
        label: 'Titulo'
        name: 'titulo'
        type: 'string'
        export: true
    a.descripcion:
        label: 'Descripcion'
        name: 'descripcion'
        type: 'string'
        export: true
    a.categoriaPadre:
        label: 'Categoriapadre'
        name: 'categoriaPadre'
        type: 'MANY_TO_ONE'
fieldsshow:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.titulo:
        label: 'Titulo'
        name: 'titulo'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.descripcion:
        label: 'Descripcion'
        name: 'descripcion'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.subCategorias:
        label: 'Subcategorias'
        name: 'subCategorias'
        type: 'ONE_TO_MANY'
        #class: 'col-lg-12'
        #closerow: true
    a.categoriaPadre:
        label: 'Categoriapadre'
        name: 'categoriaPadre'
        type: 'MANY_TO_ONE'
        #class: 'col-lg-12'
        #closerow: true
