entityName: 'Estacion'
entity: 'BackendBundle\Entity\Estacion'
repository: 'BackendBundle:Estacion'
paginate: true
index: 'estacion'
view_index: 'BackendBundle:estacion:index.html.twig'
new: 'estacion_new'
create: 'estacion_create'
view_new: 'BackendBundle:estacion:new.html.twig'
edit: 'estacion_edit'
update: 'estacion_update'
view_edit: 'BackendBundle:estacion:edit.html.twig'
show: 'estacion_show'
view_show: 'BackendBundle:estacion:show.html.twig'
delete: 'estacion_delete'
export: 'estacion_export'
sessionFilter: 'EstacionControllerFilter'
saveAndAdd: true
validator: true
fieldsindex:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        export: true
    a.titulo:
        label: 'Titulo'
        name: 'titulo'
        type: 'string'
        export: true
    a.fecha:
        label: 'Fecha'
        name: 'fecha'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.titulo:
        label: 'Titulo'
        name: 'titulo'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.fecha:
        label: 'Fecha'
        name: 'fecha'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12 col-md-12'
        #closerow: true