entityName: 'Producto'
entity: 'BackendBundle\Entity\Producto'
repository: 'BackendBundle:Producto'
paginate: true
index: 'producto'
view_index: 'BackendBundle:producto:index.html.twig'
new: 'producto_new'
create: 'producto_create'
view_new: 'BackendBundle:producto:new.html.twig'
edit: 'producto_edit'
update: 'producto_update'
view_edit: 'BackendBundle:producto:edit.html.twig'
show: 'producto_show'
view_show: 'BackendBundle:producto:show.html.twig'
delete: 'producto_delete'
export: 'producto_export'
sessionFilter: 'ProductoControllerFilter'
saveAndAdd: true
validator: true
fieldsindex:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        export: true
    a.precio:
        label: 'Precio'
        name: 'precio'
        type: 'string'
        export: true
    a.color:
        label: 'Color'
        name: 'color'
        type: 'string'
        export: true
    a.fechaCreacion:
        label: 'Fechacreacion'
        name: 'fechaCreacion'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
    a.fechaModificacion:
        label: 'Fechamodificacion'
        name: 'fechaModificacion'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
    a.stock:
        label: 'Stock'
        name: 'stock'
        type: 'integer'
        export: true
    a.esNovedad:
        label: 'Esnovedad'
        name: 'esNovedad'
        type: 'boolean'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.precio:
        label: 'Precio'
        name: 'precio'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.color:
        label: 'Color'
        name: 'color'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.fechaCreacion:
        label: 'Fechacreacion'
        name: 'fechaCreacion'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.fechaModificacion:
        label: 'Fechamodificacion'
        name: 'fechaModificacion'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.stock:
        label: 'Stock'
        name: 'stock'
        type: 'integer'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.esNovedad:
        label: 'Esnovedad'
        name: 'esNovedad'
        type: 'boolean'
        #class: 'col-lg-12 col-md-12'
        #closerow: true